### PR TITLE
lis-rpm-build: Modification to handle 32 & 64 bit VMs separately for lis build

### PR DESCRIPTION
**Pull request by johnsongeorge-w**

### CODE REVIEW

**Comment by johnsongeorge-w** [comment]
@iamshital : Review the update.

**Comment by johnsongeorge-w** [comment]
@prashantmhetar : Review the changes.

**Comment by johnsongeorge-w** [comment]
> Do we expect to have Build for both x32 and x64?

No.

**Comment by santoshx** [comment]
@harz566 please take a look

**Pull request merged**
