### PR TITLE
Keep the linux-next VM of boot_test_small stage, use a different RGIdentifier for it

### PR DESCRIPTION
**Pull request by lizzha**

### CODE REVIEW

**Comment by ader1990** [comment]
Hello @lizzha ,

This PR will keep the VM on centos and ubuntu, is this desired?

**Comment by lizzha** [comment]
Updated to keep the VM for ubuntu only.
But please hold on merging this PR, as Simon asked to keep the source code folder for the VMs kept.
I'm working on this change

**Comment by lizzha** [comment]
It's hard to keep the source folder in the VM, as kernel is built on the slave VM, so currently I will not add additional change to the pipeline.

**Comment by lizzha** [comment]
Please do not merge this PR, as design changed

**Comment by chvalean** [comment]
> It's hard to keep the source folder in the VM, as kernel is built on the slave VM, so currently I will not add additional change to the pipeline.

You just have to copy / not exclude the source package and install it, it will go in the distro default src folder.
So sources do get packaged as well as part of the build process.

**Comment by lizzha** [comment]
yes there's src package in the VM. but what we really need is the original source folder cloned from git, and has the compilation history, so that it would be quick to apply patches and build the kernel again

**Pull request closed without merging**
